-- TuneCheck - baza danych quizdb (struktura + kategorie i pytania)
-- Import: mysql -u root < database/quizdb.sql   albo phpMyAdmin -> Import
-- Konto demo administratora: login admin, haslo tunecheck
-- Tabela scores jest pusta (wyniki zapisuje aplikacja).


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE DATABASE /*!32312 IF NOT EXISTS*/ `quizdb` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */;

USE `quizdb`;
DROP TABLE IF EXISTS `admins`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `admins` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  `token` varchar(64) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `categories`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `categories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `theme_order` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=48 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `questions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `questions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `category_id` int(11) NOT NULL,
  `question_text` text NOT NULL,
  `answerA` varchar(255) NOT NULL,
  `answerB` varchar(255) NOT NULL,
  `answerC` varchar(255) NOT NULL,
  `answerD` varchar(255) NOT NULL,
  `correct_answer` char(1) NOT NULL,
  `image_url` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_questions_category` (`category_id`),
  CONSTRAINT `fk_questions_category` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=455 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `scores`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `scores` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `category_id` int(11) NOT NULL,
  `score` int(11) NOT NULL,
  `total` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

LOCK TABLES `categories` WRITE;
/*!40000 ALTER TABLE `categories` DISABLE KEYS */;
INSERT INTO `categories` VALUES (1,'A$AP Rocky',NULL);
INSERT INTO `categories` VALUES (2,'Future',NULL);
INSERT INTO `categories` VALUES (3,'Lil Uzi Vert',NULL);
INSERT INTO `categories` VALUES (4,'Playboi Carti',NULL);
INSERT INTO `categories` VALUES (5,'21 Savage',NULL);
INSERT INTO `categories` VALUES (6,'Chief Keef',NULL);
INSERT INTO `categories` VALUES (7,'Don Toliver',NULL);
INSERT INTO `categories` VALUES (8,'Drake',NULL);
INSERT INTO `categories` VALUES (9,'Gunna',NULL);
INSERT INTO `categories` VALUES (10,'Juice WRLD',NULL);
INSERT INTO `categories` VALUES (11,'Kanye West',NULL);
INSERT INTO `categories` VALUES (12,'Ken Carson',NULL);
INSERT INTO `categories` VALUES (13,'Kendrick Lamar',NULL);
INSERT INTO `categories` VALUES (14,'Kid Cudi',NULL);
INSERT INTO `categories` VALUES (15,'Lil Baby',NULL);
INSERT INTO `categories` VALUES (16,'Metro Boomin',NULL);
INSERT INTO `categories` VALUES (17,'Migos',NULL);
INSERT INTO `categories` VALUES (18,'Pop Smoke',NULL);
INSERT INTO `categories` VALUES (19,'Travis Scott',NULL);
INSERT INTO `categories` VALUES (20,'Trippie Redd',NULL);
INSERT INTO `categories` VALUES (21,'Tyler, The Creator',NULL);
INSERT INTO `categories` VALUES (22,'Young Thug',NULL);
INSERT INTO `categories` VALUES (23,'Lata 90.',4);
INSERT INTO `categories` VALUES (24,'Lata 2000.',3);
INSERT INTO `categories` VALUES (25,'Lata 2010.',2);
INSERT INTO `categories` VALUES (26,'Lata 2020.',1);
INSERT INTO `categories` VALUES (27,'Beefy i konflikty',5);
INSERT INTO `categories` VALUES (28,'Featy i kolaboracje',5);
INSERT INTO `categories` VALUES (29,'2Pac',NULL);
INSERT INTO `categories` VALUES (30,'Notorious B.I.G.',NULL);
INSERT INTO `categories` VALUES (31,'Nas',NULL);
INSERT INTO `categories` VALUES (32,'Dr. Dre',NULL);
INSERT INTO `categories` VALUES (33,'Snoop Dogg',NULL);
INSERT INTO `categories` VALUES (36,'Eminem',NULL);
INSERT INTO `categories` VALUES (37,'50 Cent',NULL);
INSERT INTO `categories` VALUES (38,'Jay-Z',NULL);
INSERT INTO `categories` VALUES (39,'Lil Wayne',NULL);
INSERT INTO `categories` VALUES (40,'OutKast',NULL);
INSERT INTO `categories` VALUES (41,'Alter ego i ksywki',5);
INSERT INTO `categories` VALUES (42,'Debiutanckie albumy',5);
INSERT INTO `categories` VALUES (43,'Ice Cube',NULL);
INSERT INTO `categories` VALUES (44,'N.W.A',NULL);
INSERT INTO `categories` VALUES (45,'Destroy Lonely',NULL);
INSERT INTO `categories` VALUES (46,'Yeat',NULL);
/*!40000 ALTER TABLE `categories` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `questions` WRITE;
/*!40000 ALTER TABLE `questions` DISABLE KEYS */;
INSERT INTO `questions` VALUES (2,1,'Z jakiego miasta pochodzi A$AP Rocky?','Chicago','Nowy Jork','Los Angeles','Atlanta','B',NULL);
INSERT INTO `questions` VALUES (3,1,'Jak brzmi prawdziwe imię i nazwisko A$AP Rocky\'ego?','Calvin Broadus','Aubrey Graham','Nayvadius Wilburn','Rakim Mayers','D',NULL);
INSERT INTO `questions` VALUES (4,1,'Który hit A$AP Rocky\'ego nagrał z Drake\'iem, 2 Chainzem i Kendrickiem Lamarem?','Everyday','F**kin\' Problems','1Train','Jukebox Joints','B',NULL);
INSERT INTO `questions` VALUES (6,1,'Jak nazywał się przełomowy mixtape A$AP Rocky\'ego z 2011 roku?','Live.Love.A$AP','Cozy Tapes Vol. 1','Lord Pretty Flacko Jodye','At.Long.Last.A$AP','A',NULL);
INSERT INTO `questions` VALUES (7,2,'Jak nazywa się wspólny album Future\'a i Metro Boomina z 2024 roku?','We Don\'t Trust You','What a Time to Be Alive','Super Slimey','Pluto x Baby Pluto','A',NULL);
INSERT INTO `questions` VALUES (8,2,'Z jakiego miasta pochodzi Future?','Chicago','Atlanta','Houston','Detroit','B',NULL);
INSERT INTO `questions` VALUES (9,2,'Jak nazywa się kolektyw i wytwórnia muzyczna założona przez Future\'a?','Dreamville','Top Dawg Entertainment','Cactus Jack','Freebandz','D',NULL);
INSERT INTO `questions` VALUES (10,2,'W którym roku ukazał się przełomowy dla kariery Future\'a album DS2 (Dirty Sprite 2)?','2012','2015','2017','2019','B',NULL);
INSERT INTO `questions` VALUES (11,2,'Który utwór Future\'a z 2017 roku słynie z charakterystycznego fletu?','Mask Off','Low Life (ft. The Weeknd)','Life Is Good (ft. Drake)','Wait For U (ft. Drake & Tems)','A',NULL);
INSERT INTO `questions` VALUES (12,3,'Z którego miasta pochodzi Lil Uzi Vert?','Atlanta','Chicago','Philadelphia','Los Angeles','C',NULL);
INSERT INTO `questions` VALUES (13,3,'Z kim Lil Uzi Vert nagrał przebój Bad and Boujee?','Travis Scott','Drake','Future','Migos','D',NULL);
INSERT INTO `questions` VALUES (14,3,'Jaki charakterystyczny element wizerunku miał Lil Uzi Vert na czole?','Tatuaż krzyża','Diament','Kolczyk','Bliznę','B',NULL);
INSERT INTO `questions` VALUES (15,3,'Jak nazywa się rozszerzona wersja (deluxe) albumu Eternal Atake?','LUV vs The World 2','Eternal Atake 2','The Perfect LUV Tape','Pluto x Baby Pluto','A',NULL);
INSERT INTO `questions` VALUES (16,3,'Którym utworem z 2017 roku Lil Uzi Vert przebił się do mainstreamu?','Money Longer','20 Min','Just Wanna Rock','XO TOUR Llif3','D',NULL);
INSERT INTO `questions` VALUES (17,4,'Jak nazywa się album Playboi Cartiego z 2020 roku?','Eternal Atake','Whole Lotta Red','Red Tape','Vamp Life','B',NULL);
INSERT INTO `questions` VALUES (18,4,'Z którym kolektywem A$AP Rocky\'ego związał się Playboi Carti na początku kariery?','YSL','Cactus Jack','AWGE','OVO','C',NULL);
INSERT INTO `questions` VALUES (19,4,'Z którego miasta pochodzi Playboi Carti?','Houston','Chicago','Atlanta','Nowy Jork','C',NULL);
INSERT INTO `questions` VALUES (20,4,'Który artysta był producentem wykonawczym albumu Playboi Cartiego z 2020 roku?','Ken Carson','Travis Scott','Future','Kanye West','D',NULL);
INSERT INTO `questions` VALUES (21,4,'Jak nazywa się album Playboi Cartiego z 2018 roku?','Whole Lotta Red','Die Lit','Eternal Atake','A Great Chaos','B',NULL);
INSERT INTO `questions` VALUES (22,1,'Jaki jest pierwszy studyjny album A$AP Rocky\'ego?','TESTING','Live.Love.A$AP','Long.Live.A$AP','At.Long.Last.A$AP','C',NULL);
INSERT INTO `questions` VALUES (23,5,'W jakim kraju urodził się 21 Savage?','Stany Zjednoczone','Wielka Brytania','Jamajka','Kanada','B',NULL);
INSERT INTO `questions` VALUES (24,5,'Z jakim miastem najmocniej kojarzy się kariera 21 Savage?','Miami','Detroit','Atlanta','Memphis','C',NULL);
INSERT INTO `questions` VALUES (25,5,'Jak nazywa się wspólny album 21 Savage i Metro Boomin z 2016 roku?','Without Warning','i am > i was','Heroes & Villains','Savage Mode','D',NULL);
INSERT INTO `questions` VALUES (26,5,'Jak zatytułowany jest wspólny album 21 Savage i Drake\'a z 2022 roku?','Certified Lover Boy','More Life','Her Loss','Dark Lane Demo Tapes','C',NULL);
INSERT INTO `questions` VALUES (27,5,'Który utwór 21 Savage z gościnnym udziałem J. Cole\'a zdobył nagrodę Grammy?','Bank Account','a lot','Rockstar','Runnin','B',NULL);
INSERT INTO `questions` VALUES (28,6,'Z jakiego miasta pochodzi Chief Keef?','Chicago','Nowy Jork','Atlanta','Houston','A',NULL);
INSERT INTO `questions` VALUES (29,6,'Jak brzmi prawdziwe imię i nazwisko Chief Keefa?','Michael White','Keith Cozart','Dominique Jones','Jarad Higgins','B',NULL);
INSERT INTO `questions` VALUES (30,6,'Jak nazywa się debiutancki album studyjny Chief Keefa z 2012 roku?','Bang 3','Back from the Dead','Nobody','Finally Rich','D',NULL);
INSERT INTO `questions` VALUES (31,6,'Którego gatunku Chief Keef jest uznawany za jednego z pionierów?','Jazz rap','Crunk','Drill','Boom bap','C',NULL);
INSERT INTO `questions` VALUES (32,6,'Jaki pseudonim, obok Chief Keef, jest z nim najczęściej kojarzony?','Flacko','Sosa','Thugger','Cudder','B',NULL);
INSERT INTO `questions` VALUES (33,7,'Z jakiego miasta pochodzi Don Toliver?','Nowy Jork','Atlanta','Chicago','Houston','D',NULL);
INSERT INTO `questions` VALUES (34,7,'Do wytwórni którego artysty należy Don Toliver?','Travis Scott','Drake','Future','Kanye West','A',NULL);
INSERT INTO `questions` VALUES (35,7,'Jak nazywa się singiel, który przyniósł Donowi Toliverowi przełom?','Bandit','After Party','No Idea','Lemonade','C',NULL);
INSERT INTO `questions` VALUES (36,7,'Jak zatytułowany jest album Dona Tolivera z 2021 roku?','Life of a DON','Love Sick','Donny Womack','Hardstone Psycho','A',NULL);
INSERT INTO `questions` VALUES (37,7,'Jak brzmi prawdziwe nazwisko Dona Tolivera?','Donald Toliver','Marcus Toliver','Caleb Toliver','Darius Toliver','C',NULL);
INSERT INTO `questions` VALUES (38,8,'Z jakiego miasta pochodzi Drake?','Nowy Jork','Toronto','Londyn','Los Angeles','B',NULL);
INSERT INTO `questions` VALUES (39,8,'Jak brzmi prawdziwe imię i nazwisko Drake\'a?','Aubrey Drake Graham','Aubrey Drake Carter','Aubrey Drake Williams','Aubrey Drake Jones','A',NULL);
INSERT INTO `questions` VALUES (40,8,'W jakim serialu młodzieżowym Drake grał, zanim został raperem?','Glee','Skins','Degrassi','Riverdale','C',NULL);
INSERT INTO `questions` VALUES (41,8,'Jak nazywa się wytwórnia współzałożona przez Drake\'a?','Quality Control','Freebandz','OVO Sound','Cactus Jack','C',NULL);
INSERT INTO `questions` VALUES (42,8,'Jak zatytułowany jest album Drake\'a z 2011 roku?','Nothing Was the Same','Scorpion','Views','Take Care','D',NULL);
INSERT INTO `questions` VALUES (43,9,'Z jakiego miasta wywodzi się Gunna?','Houston','Chicago','Atlanta','Memphis','C',NULL);
INSERT INTO `questions` VALUES (44,9,'Jak brzmi prawdziwe imię i nazwisko Gunny?','Sergio Kitchens','Jeffery Williams','Keith Cozart','Dominique Jones','A',NULL);
INSERT INTO `questions` VALUES (45,9,'Jak zatytułowany jest album Gunny z 2020 roku?','a Gift & a Curse','WUNNA','Drip or Drown 2','DS4EVER','B',NULL);
INSERT INTO `questions` VALUES (46,9,'Który utwór z albumu DS4EVER stał się największym hitem Gunny?','idk nomore','25k jacket','pushin P','banking on me','C',NULL);
INSERT INTO `questions` VALUES (47,9,'Z kim Gunna nagrał przebojowy utwór Drip Too Hard?','Lil Baby','Young Thug','Future','Travis Scott','A',NULL);
INSERT INTO `questions` VALUES (48,10,'Z jakiego miasta pochodził Juice WRLD?','Atlanta','Chicago','Los Angeles','Nowy Jork','B',NULL);
INSERT INTO `questions` VALUES (49,10,'Jak brzmiało prawdziwe imię i nazwisko Juice WRLD?','Scott Mescudi','Michael White','Bashar Jackson','Jarad Higgins','D',NULL);
INSERT INTO `questions` VALUES (50,10,'Który singiel przyniósł Juice WRLD światową sławę?','Lucid Dreams','Come & Go','Righteous','Robbery','A',NULL);
INSERT INTO `questions` VALUES (51,10,'Jak zatytułowany jest pierwszy pośmiertny album Juice WRLD z 2020 roku?','Fighting Demons','Legends Never Die','Goodbye & Good Riddance','Death Race for Love','B',NULL);
INSERT INTO `questions` VALUES (52,10,'Z którym raperem Juice WRLD nagrał wspólny album WRLD on Drugs?','Young Thug','Trippie Redd','Lil Uzi Vert','Future','D',NULL);
INSERT INTO `questions` VALUES (53,11,'W jakim mieście wychował się Kanye West?','Atlanta','Chicago','Nowy Jork','Detroit','B',NULL);
INSERT INTO `questions` VALUES (54,11,'Jak zatytułowany jest debiutancki album Kanye Westa z 2004 roku?','808s & Heartbreak','The College Dropout','Graduation','Late Registration','B',NULL);
INSERT INTO `questions` VALUES (55,11,'Jak nazywa się wytwórnia założona przez Kanye Westa?','G.O.O.D. Music','Top Dawg Entertainment','Roc Nation','Dreamville','A',NULL);
INSERT INTO `questions` VALUES (56,11,'Który album Kanye Westa z 2010 roku jest najczęściej uznawany za jego opus magnum?','Donda','My Beautiful Dark Twisted Fantasy','Yeezus','The Life of Pablo','B',NULL);
INSERT INTO `questions` VALUES (57,11,'Na jakie imię Kanye West oficjalnie zmienił w 2021 roku swoje imię i nazwisko?','Pablo','Ye','Louis','Yeezy','B',NULL);
INSERT INTO `questions` VALUES (58,12,'Jak nazywa się debiutancki album Kena Carsona z 2021 roku?','X','A Great Chaos','Project X','Teen X','C',NULL);
INSERT INTO `questions` VALUES (59,12,'Jak nazywa się wytwórnia, w której nagrywa Ken Carson?','Cactus Jack','Freebandz','Generation Now','Opium','D',NULL);
INSERT INTO `questions` VALUES (60,12,'Z jakim miastem związany jest Ken Carson?','Los Angeles','Houston','Atlanta','Nowy Jork','C',NULL);
INSERT INTO `questions` VALUES (61,12,'Jak zatytułowany jest album Kena Carsona z 2023 roku?','Teen X','Project X','X','A Great Chaos','D',NULL);
INSERT INTO `questions` VALUES (62,12,'Jak zatytułowany jest album Kena Carsona wydany w 2022 roku?','More Chaos','X','Whole Lotta Red','Die Lit','B',NULL);
INSERT INTO `questions` VALUES (63,13,'Z jakiego miasta pochodzi Kendrick Lamar?','Compton','Long Beach','Oakland','Inglewood','A',NULL);
INSERT INTO `questions` VALUES (64,13,'Jak nazywa się wytwórnia, z którą Kendrick Lamar był związany przez większość kariery?','Bad Boy Records','Dreamville','Top Dawg Entertainment','Death Row','C',NULL);
INSERT INTO `questions` VALUES (65,13,'Za który album Kendrick Lamar otrzymał Nagrodę Pulitzera?','good kid, m.A.A.d city','To Pimp a Butterfly','Mr. Morale & the Big Steppers','DAMN.','D',NULL);
INSERT INTO `questions` VALUES (66,13,'Jak zatytułowany jest przełomowy album Kendricka Lamara z 2012 roku?','untitled unmastered.','good kid, m.A.A.d city','GNX','Section.80','B',NULL);
INSERT INTO `questions` VALUES (67,13,'Który utwór Kendricka Lamara z 2024 roku był częścią głośnego konfliktu z Drakiem?','HUMBLE.','Money Trees','Not Like Us','Alright','C',NULL);
INSERT INTO `questions` VALUES (68,14,'Z jakiego miasta pochodzi Kid Cudi?','Chicago','Cleveland','Pittsburgh','Detroit','B',NULL);
INSERT INTO `questions` VALUES (69,14,'Jak brzmi prawdziwe imię i nazwisko Kid Cudiego?','Scott Mescudi','Kevin Mescudi','Brian Mescudi','Anthony Mescudi','A',NULL);
INSERT INTO `questions` VALUES (70,14,'Jak zatytułowany jest debiutancki album Kid Cudiego z 2009 roku?','Speedin\' Bullet 2 Heaven','Man on the Moon: The End of Day','Satellite Flight','Indicud','B',NULL);
INSERT INTO `questions` VALUES (71,14,'Jak nazywa się wspólny album Kid Cudiego i Kanye Westa z 2018 roku?','Jesus Is King','Cruel Summer','Kids See Ghosts','Watch the Throne','C',NULL);
INSERT INTO `questions` VALUES (72,14,'Który singiel przyniósł Kid Cudiemu pierwszy duży rozgłos?','Soundtrack 2 My Life','Erase Me','Day \'n\' Nite','Pursuit of Happiness','C',NULL);
INSERT INTO `questions` VALUES (73,15,'Z jakiego miasta pochodzi Lil Baby?','Nowy Jork','Baton Rouge','Atlanta','Memphis','C',NULL);
INSERT INTO `questions` VALUES (74,15,'Jak brzmi prawdziwe imię i nazwisko Lil Baby\'ego?','Keith Cozart','Sergio Kitchens','Jeffery Williams','Dominique Jones','D',NULL);
INSERT INTO `questions` VALUES (75,15,'Jak zatytułowany jest album Lil Baby\'ego z 2020 roku?','Drip Harder','It\'s Only Me','My Turn','Harder Than Ever','C',NULL);
INSERT INTO `questions` VALUES (76,15,'Jak nazywa się wytwórnia, z którą związany jest Lil Baby?','Cactus Jack','Quality Control','YSL','OVO Sound','B',NULL);
INSERT INTO `questions` VALUES (77,15,'Który utwór Lil Baby\'ego z 2020 roku powstał jako komentarz do protestów w USA?','Woah','Emotionally Scarred','The Bigger Picture','Drip Too Hard','C',NULL);
INSERT INTO `questions` VALUES (78,16,'Do jakiego filmu z 2023 roku Metro Boomin przygotował album ze ścieżką dźwiękową?','Creed III','Oppenheimer','Spider-Man: Poprzez multiwersum','Barbie','C',NULL);
INSERT INTO `questions` VALUES (79,16,'Z jakiego miasta pochodzi Metro Boomin?','St. Louis','Atlanta','Nowy Jork','Chicago','A',NULL);
INSERT INTO `questions` VALUES (80,16,'Jak brzmi prawdziwe imię i nazwisko Metro Boomina?','Michael White','Caleb Toliver','Leland Wayne','Keith Cozart','C',NULL);
INSERT INTO `questions` VALUES (81,16,'Jak nazywa się pierwszy solowy album Metro Boomina z 2018 roku?','Heroes & Villains','Savage Mode','Double or Nothing','Not All Heroes Wear Capes','D',NULL);
INSERT INTO `questions` VALUES (82,16,'Jak zatytułowany jest solowy album Metro Boomina z 2022 roku?','We Don\'t Trust You','Not All Heroes Wear Capes','Double or Nothing','Heroes & Villains','D',NULL);
INSERT INTO `questions` VALUES (83,17,'Który utwór z 2013 roku przyniósł Migos pierwszy duży rozgłos?','Bad and Boujee','Stir Fry','Walk It Talk It','Versace','D',NULL);
INSERT INTO `questions` VALUES (84,17,'Którzy raperzy tworzyli grupę Migos?','Quavo, Gunna i Offset','Offset, Takeoff i Lil Baby','Quavo, Offset i Takeoff','Quavo, Takeoff i Young Thug','C',NULL);
INSERT INTO `questions` VALUES (85,17,'Jak zatytułowany jest przełomowy album Migos z 2017 roku?','Culture II','Yung Rich Nation','Culture III','Culture','D',NULL);
INSERT INTO `questions` VALUES (86,17,'Który utwór Migos dotarł na pierwsze miejsce listy Billboard Hot 100?','Bad and Boujee','Stir Fry','Walk It Talk It','MotorSport','A',NULL);
INSERT INTO `questions` VALUES (87,17,'Z jakiego stanu pochodzi grupa Migos?','Georgia','Teksas','Illinois','Nowy Jork','A',NULL);
INSERT INTO `questions` VALUES (88,18,'Z jakiej dzielnicy Nowego Jorku pochodził Pop Smoke?','Harlem','Brooklyn','Bronx','Queens','B',NULL);
INSERT INTO `questions` VALUES (89,18,'Jak brzmiało prawdziwe imię i nazwisko Popa Smoke\'a?','Michael White','Bashar Jackson','Jarad Higgins','Keith Cozart','B',NULL);
INSERT INTO `questions` VALUES (90,18,'Jak zatytułowany jest pośmiertny album Popa Smoke\'a z 2020 roku?','Meet the Woo','Faith','Shoot for the Stars, Aim for the Moon','Welcome to the Party','C',NULL);
INSERT INTO `questions` VALUES (91,18,'Którego gatunku Pop Smoke był czołową postacią?','Trap','Drill','G-funk','Boom bap','B',NULL);
INSERT INTO `questions` VALUES (92,18,'Który znany raper był producentem wykonawczym pośmiertnego albumu Popa Smoke\'a?','Kanye West','Jay-Z','Drake','50 Cent','D',NULL);
INSERT INTO `questions` VALUES (93,19,'Z jakiego miasta pochodzi Travis Scott?','Houston','Los Angeles','Nowy Jork','Atlanta','A',NULL);
INSERT INTO `questions` VALUES (94,19,'Jak brzmi prawdziwe imię i nazwisko Travisa Scotta?','Jacques Webster','Caleb Toliver','Rakim Mayers','Sergio Kitchens','A',NULL);
INSERT INTO `questions` VALUES (95,19,'Jak zatytułowany jest album Travisa Scotta z 2018 roku?','Utopia','Astroworld','Birds in the Trap Sing McKnight','Rodeo','B',NULL);
INSERT INTO `questions` VALUES (96,19,'Jak nazywa się wytwórnia założona przez Travisa Scotta?','Freebandz','Dreamville','Opium','Cactus Jack','D',NULL);
INSERT INTO `questions` VALUES (97,19,'Jak zatytułowany jest album Travisa Scotta wydany w 2023 roku?','Utopia','Jackboys','Days Before Rodeo','Owl Pharaoh','A',NULL);
INSERT INTO `questions` VALUES (98,20,'Z jakiego stanu pochodzi Trippie Redd?','Ohio','Teksas','Georgia','Floryda','A',NULL);
INSERT INTO `questions` VALUES (99,20,'Jak brzmi prawdziwe imię i nazwisko Trippie Redda?','Michael White','Bashar Jackson','Scott Mescudi','Jarad Higgins','A',NULL);
INSERT INTO `questions` VALUES (100,20,'Jak zatytułowany jest debiutancki album studyjny Trippie Redda z 2018 roku?','Pegasus','Trip at Knight','A Love Letter to You','Life\'s a Trip','D',NULL);
INSERT INTO `questions` VALUES (101,20,'Z którym raperem Trippie Redd nagrał utwór Dark Knight Dummo?','Lil Uzi Vert','Juice WRLD','Playboi Carti','Travis Scott','D',NULL);
INSERT INTO `questions` VALUES (102,20,'Jak zatytułowany jest album Trippie Redda z 2020 roku?','Pegasus','Neon Shark vs Pegasus','Mansion Musik','!','A',NULL);
INSERT INTO `questions` VALUES (103,21,'Jak nazywa się kolektyw współzałożony przez Tylera, The Creatora?','Brockhampton','TDE','A$AP Mob','Odd Future','D',NULL);
INSERT INTO `questions` VALUES (104,21,'Za który album Tyler, The Creator zdobył nagrodę Grammy w 2020 roku?','Flower Boy','IGOR','Cherry Bomb','Wolf','B',NULL);
INSERT INTO `questions` VALUES (105,21,'Z jakiego miasta pochodzi Tyler, The Creator?','Los Angeles','Atlanta','Nowy Jork','Chicago','A',NULL);
INSERT INTO `questions` VALUES (106,21,'Jak brzmi prawdziwe imię i nazwisko Tylera, The Creatora?','Tyler Williams','Tyler Mescudi','Tyler Graham','Tyler Okonma','D',NULL);
INSERT INTO `questions` VALUES (107,21,'Jak zatytułowany jest album Tylera, The Creatora z 2021 roku?','Goblin','Call Me If You Get Lost','Chromakopia','Flower Boy','B',NULL);
INSERT INTO `questions` VALUES (108,22,'Z jakiego miasta pochodzi Young Thug?','Chicago','Houston','Atlanta','Memphis','C',NULL);
INSERT INTO `questions` VALUES (109,22,'Jak brzmi prawdziwe imię i nazwisko Younga Thuga?','Jeffery Williams','Sergio Kitchens','Dominique Jones','Keith Cozart','A',NULL);
INSERT INTO `questions` VALUES (110,22,'Jak nazywa się wytwórnia i kolektyw założony przez Younga Thuga?','Cactus Jack','Opium','YSL','Freebandz','C',NULL);
INSERT INTO `questions` VALUES (111,22,'Który album Younga Thuga jako pierwszy dotarł na szczyt Billboard 200?','Punk','Beautiful Thugger Girls','So Much Fun','Barter 6','C',NULL);
INSERT INTO `questions` VALUES (112,22,'Jak zatytułowany jest mixtape Younga Thuga z 2015 roku?','Barter 6','I\'m Up','Beautiful Thugger Girls','Punk','A',NULL);
INSERT INTO `questions` VALUES (113,23,'Jak nazywa się debiutancki album Nasa z 1994 roku?','Reasonable Doubt','Illmatic','The Chronic','Ready to Die','B',NULL);
INSERT INTO `questions` VALUES (114,23,'Która wytwórnia wydawała w latach 90. albumy Dr. Dre i Snoop Dogga?','Def Jam','Death Row Records','Roc-A-Fella Records','Bad Boy Records','B',NULL);
INSERT INTO `questions` VALUES (115,23,'Który raper podpisał w 1995 roku kontrakt z wytwórnią Suge Knighta?','Nas','Notorious B.I.G.','Jay-Z','2Pac','D',NULL);
INSERT INTO `questions` VALUES (116,23,'Który duet z Atlanty wydał w 1994 roku album Southernplayalisticadillacmuzik?','OutKast','UGK','Goodie Mob','Eightball & MJG','A',NULL);
INSERT INTO `questions` VALUES (117,23,'Który album Dr. Dre z 1992 roku spopularyzował brzmienie G-funk?','The Chronic','Straight Outta Compton','Doggystyle','2001','A',NULL);
INSERT INTO `questions` VALUES (118,24,'Jak nazywa się debiutancki album 50 Centa z 2003 roku?','Get Rich or Die Tryin\'','Curtis','The Massacre','Before I Self Destruct','A',NULL);
INSERT INTO `questions` VALUES (119,24,'W jakim filmie z 2002 roku Eminem zagrał główną rolę?','Hustle & Flow','Notorious','8 Mile','Straight Outta Compton','C',NULL);
INSERT INTO `questions` VALUES (120,24,'Który utwór Eminema jako pierwszy utwór rapowy zdobył Oscara za najlepszą piosenkę?','Without Me','The Real Slim Shady','Stan','Lose Yourself','D',NULL);
INSERT INTO `questions` VALUES (121,24,'Który album Lil Wayne\'a z 2008 roku sprzedał się w ponad milionie kopii w tydzień?','Tha Carter III','Tha Carter II','Rebirth','Tha Carter IV','A',NULL);
INSERT INTO `questions` VALUES (122,24,'Który raper w 2007 roku wygrał z 50 Centem pojedynek na sprzedaż albumów?','Jay-Z','Kanye West','Lil Wayne','Eminem','B',NULL);
INSERT INTO `questions` VALUES (123,25,'Która grupa spopularyzowała w latach 2010. charakterystyczny dla trapu „triplet flow”?','N.W.A','Migos','OutKast','Wu-Tang Clan','B',NULL);
INSERT INTO `questions` VALUES (124,25,'Który album Kendricka Lamara z 2015 roku łączył rap z jazzem i funkiem?','DAMN.','good kid, m.A.A.d city','Section.80','To Pimp a Butterfly','D',NULL);
INSERT INTO `questions` VALUES (125,25,'Który singiel Drake\'a z 2015 roku zasłynął teledyskiem z tańcem na kolorowym tle?','God\'s Plan','Started from the Bottom','One Dance','Hotline Bling','D',NULL);
INSERT INTO `questions` VALUES (126,25,'Który raper wydał w 2016 roku album The Life of Pablo?','Drake','Travis Scott','Kanye West','Kid Cudi','C',NULL);
INSERT INTO `questions` VALUES (127,25,'Jak nazywa się album Drake\'a z 2018 roku?','Views','More Life','Scorpion','Take Care','C',NULL);
INSERT INTO `questions` VALUES (128,26,'W jakim mieście Kendrick Lamar wystąpił w przerwie Super Bowl w lutym 2025 roku?','Las Vegas','Nowy Orlean','Miami','Los Angeles','B',NULL);
INSERT INTO `questions` VALUES (129,26,'Jak nazywa się album Kendricka Lamara z 2024 roku?','Mr. Morale & the Big Steppers','GNX','DAMN.','To Pimp a Butterfly','B',NULL);
INSERT INTO `questions` VALUES (130,26,'Który raper wydał w 2021 roku album Donda, nazwany na cześć swojej matki?','Kanye West','Travis Scott','Drake','J. Cole','A',NULL);
INSERT INTO `questions` VALUES (131,26,'Jak nazywa się album Drake\'a z 2021 roku?','Scorpion','Certified Lover Boy','Take Care','Views','B',NULL);
INSERT INTO `questions` VALUES (132,26,'Jak nazywa się album Tylera, The Creatora z 2024 roku?','Chromakopia','Flower Boy','Call Me If You Get Lost','IGOR','A',NULL);
INSERT INTO `questions` VALUES (133,27,'Między którymi wytwórniami toczył się w latach 90. konflikt Wschód–Zachód?','Cash Money i No Limit','Aftermath i Shady','Def Jam i Roc-A-Fella','Bad Boy i Death Row','D',NULL);
INSERT INTO `questions` VALUES (134,27,'Jakim utworem Nas odpowiedział w 2001 roku na „Takeover” Jay-Z?','Back to Back','No Vaseline','Ether','Hit \'Em Up','C',NULL);
INSERT INTO `questions` VALUES (135,27,'Który utwór 2Pac nagrał przeciwko Notorious B.I.G. i wytwórni Bad Boy?','Hit \'Em Up','Ether','No Vaseline','Takeover','A',NULL);
INSERT INTO `questions` VALUES (136,27,'Jakim utworem Drake odpowiedział w 2024 roku na ataki Kendricka Lamara?','Not Like Us','Back to Back','Ether','Family Matters','D',NULL);
INSERT INTO `questions` VALUES (137,27,'Który utwór Ice Cube\'a z 1991 roku był atakiem na jego dawną grupę N.W.A?','Ether','Takeover','Hit \'Em Up','No Vaseline','D',NULL);
INSERT INTO `questions` VALUES (138,28,'Kto gościnnie występuje w utworze goosebumps Travisa Scotta?','Drake','Kid Cudi','Kendrick Lamar','Young Thug','C',NULL);
INSERT INTO `questions` VALUES (139,28,'Z kim Jay-Z nagrał wspólny album Watch the Throne (2011)?','Pharrell','Nas','Kanye West','Drake','C',NULL);
INSERT INTO `questions` VALUES (140,28,'Który raper gościnnie występuje w utworze Forgot About Dre Dr. Dre?','Snoop Dogg','50 Cent','Eminem','2Pac','C',NULL);
INSERT INTO `questions` VALUES (141,28,'Na którym albumie Travisa Scotta znalazł się utwór SICKO MODE z udziałem Drake\'a?','Astroworld','Rodeo','Utopia','Birds in the Trap Sing McKnight','A',NULL);
INSERT INTO `questions` VALUES (142,28,'Z kim Drake nagrał wspólny mixtape What a Time to Be Alive (2015)?','Travis Scott','Future','21 Savage','Lil Wayne','B',NULL);
INSERT INTO `questions` VALUES (143,29,'Jak brzmi prawdziwe imię i nazwisko 2Paca?','Tupac Williams','Tupac Jackson','Tupac Carter','Tupac Shakur','D',NULL);
INSERT INTO `questions` VALUES (144,29,'W jakim mieście urodził się 2Pac?','Baltimore','Los Angeles','Nowy Jork','Oakland','C',NULL);
INSERT INTO `questions` VALUES (145,29,'Który album 2Paca był jednym z pierwszych podwójnych albumów studyjnych w rapie?','2Pacalypse Now','Me Against the World','Strictly 4 My N.I.G.G.A.Z.','All Eyez on Me','D',NULL);
INSERT INTO `questions` VALUES (146,29,'Pod jakim pseudonimem ukazał się album The Don Killuminati: The 7 Day Theory?','Thug Life','Pac-Man','Makaveli','Outlawz','C',NULL);
INSERT INTO `questions` VALUES (147,29,'Który utwór 2Paca z gościnnym udziałem Dr. Dre stał się hymnem Kalifornii?','California Love','Dear Mama','Hit \'Em Up','Changes','A',NULL);
INSERT INTO `questions` VALUES (148,30,'Jak brzmi prawdziwe imię i nazwisko Notorious B.I.G.?','Tupac Shakur','Shawn Carter','Christopher Wallace','Earl Simmons','C',NULL);
INSERT INTO `questions` VALUES (149,30,'Z jakiej dzielnicy Nowego Jorku pochodził Notorious B.I.G.?','Queens','Bronx','Brooklyn','Harlem','C',NULL);
INSERT INTO `questions` VALUES (150,30,'Jak nazywa się debiutancki album Notorious B.I.G. z 1994 roku?','Illmatic','Reasonable Doubt','Ready to Die','Life After Death','C',NULL);
INSERT INTO `questions` VALUES (151,30,'Jakiego innego pseudonimu używał Notorious B.I.G.?','Big L','Big Pun','Fat Joe','Biggie Smalls','D',NULL);
INSERT INTO `questions` VALUES (152,30,'Który podwójny album Notorious B.I.G. ukazał się w 1997 roku?','Life After Death','Born Again','Duets: The Final Chapter','Ready to Die','A',NULL);
INSERT INTO `questions` VALUES (153,31,'Jak brzmi prawdziwe imię i nazwisko Nasa?','Nasir Williams','Nasir Carter','Nasir Jones','Nasir Jackson','C',NULL);
INSERT INTO `questions` VALUES (154,31,'Z jakiej dzielnicy Nowego Jorku pochodzi Nas?','Bronx','Queens','Staten Island','Brooklyn','B',NULL);
INSERT INTO `questions` VALUES (155,31,'Jak nazywa się album Nasa z 1996 roku z przebojem If I Ruled the World?','God\'s Son','It Was Written','Stillmatic','Illmatic','B',NULL);
INSERT INTO `questions` VALUES (156,31,'Jak nazywa się album Nasa z 2001 roku, uznawany za jego wielki powrót?','Stillmatic','Illmatic','God\'s Son','King\'s Disease','A',NULL);
INSERT INTO `questions` VALUES (157,31,'Za który album Nas zdobył swoją pierwszą nagrodę Grammy w 2021 roku?','King\'s Disease','Stillmatic','Illmatic','Hip Hop Is Dead','A',NULL);
INSERT INTO `questions` VALUES (158,32,'Jak brzmi prawdziwe imię i nazwisko Dr. Dre?','O\'Shea Jackson','Curtis Jackson','Calvin Broadus','Andre Young','D',NULL);
INSERT INTO `questions` VALUES (159,32,'Członkiem której legendarnej grupy był Dr. Dre?','Wu-Tang Clan','Run-DMC','Public Enemy','N.W.A','D',NULL);
INSERT INTO `questions` VALUES (160,32,'Jak nazywa się wytwórnia założona przez Dr. Dre w 1996 roku?','Bad Boy Records','Shady Records','Death Row Records','Aftermath Entertainment','D',NULL);
INSERT INTO `questions` VALUES (161,32,'Jak nazywa się album Dr. Dre wydany w 1999 roku?','Compton','2001','Doggystyle','The Chronic','B',NULL);
INSERT INTO `questions` VALUES (162,32,'Jaką markę słuchawek współzałożył Dr. Dre?','Sennheiser','Beats','Bose','Skullcandy','B',NULL);
INSERT INTO `questions` VALUES (163,33,'Jak brzmi prawdziwe imię i nazwisko Snoop Dogga?','Earl Simmons','Calvin Broadus','Dwayne Carter','Andre Young','B',NULL);
INSERT INTO `questions` VALUES (164,33,'Z jakiego miasta w Kalifornii pochodzi Snoop Dogg?','Oakland','Long Beach','Compton','Inglewood','B',NULL);
INSERT INTO `questions` VALUES (165,33,'Jak nazywa się debiutancki album Snoop Dogga z 1993 roku?','Doggystyle','Tha Last Meal','The Chronic','Tha Doggfather','A',NULL);
INSERT INTO `questions` VALUES (166,33,'Który producent wprowadził Snoop Dogga na scenę, zapraszając go na swój album The Chronic?','DJ Quik','Dr. Dre','Timbaland','Pharrell','B',NULL);
INSERT INTO `questions` VALUES (167,33,'Z kim Snoop Dogg nagrał przebój Drop It Like It\'s Hot (2004)?','Dr. Dre','Pharrell','Akon','50 Cent','B',NULL);
INSERT INTO `questions` VALUES (178,36,'Jak nazywa się pierwszy album Eminema, wydany w 1996 roku?','Infinite','The Slim Shady LP','Relapse','Encore','A',NULL);
INSERT INTO `questions` VALUES (179,36,'Z jakiego miasta pochodzi Eminem?','Cleveland','Chicago','Detroit','Nowy Jork','C',NULL);
INSERT INTO `questions` VALUES (180,36,'Jak nazywa się album Eminema wydany w grudniu 2017 roku?','Recovery','Encore','Revival','Kamikaze','C',NULL);
INSERT INTO `questions` VALUES (181,36,'Który producent odkrył Eminema i podpisał z nim kontrakt?','Kanye West','Pharrell','Timbaland','Dr. Dre','D',NULL);
INSERT INTO `questions` VALUES (182,36,'Jak nazywa się album Eminema z 2000 roku?','Encore','The Marshall Mathers LP','The Eminem Show','The Slim Shady LP','B',NULL);
INSERT INTO `questions` VALUES (183,37,'Jak brzmi prawdziwe imię i nazwisko 50 Centa?','Curtis Jackson','Shawn Carter','Marshall Mathers','Earl Simmons','A',NULL);
INSERT INTO `questions` VALUES (184,37,'Z jakiej dzielnicy Nowego Jorku pochodzi 50 Cent?','Queens','Harlem','Bronx','Brooklyn','A',NULL);
INSERT INTO `questions` VALUES (185,37,'Który singiel 50 Centa wyprodukowany przez Dr. Dre stał się jego największym przebojem?','Candy Shop','P.I.M.P.','In da Club','21 Questions','C',NULL);
INSERT INTO `questions` VALUES (186,37,'Jak nazywa się grupa i wytwórnia założona przez 50 Centa?','G-Unit','Young Money','Ruff Ryders','Shady Records','A',NULL);
INSERT INTO `questions` VALUES (187,37,'Którego rapera 50 Cent wyrzucił w 2005 roku ze swojej grupy?','The Game','Ja Rule','Busta Rhymes','Eminem','A',NULL);
INSERT INTO `questions` VALUES (188,38,'Jak brzmi prawdziwe imię i nazwisko Jay-Z?','Dwayne Carter','Shawn Carter','Nasir Jones','Christopher Wallace','B',NULL);
INSERT INTO `questions` VALUES (189,38,'Z jakiej dzielnicy Nowego Jorku pochodzi Jay-Z?','Queens','Brooklyn','Bronx','Harlem','B',NULL);
INSERT INTO `questions` VALUES (190,38,'Jak nazywa się debiutancki album Jay-Z z 1996 roku?','The Black Album','The Blueprint','Vol. 2... Hard Knock Life','Reasonable Doubt','D',NULL);
INSERT INTO `questions` VALUES (191,38,'Jaką wytwórnię Jay-Z współzałożył w 1995 roku?','Roc-A-Fella Records','Death Row Records','Bad Boy Records','Def Jam','A',NULL);
INSERT INTO `questions` VALUES (192,38,'Z kim Jay-Z nagrał przebój Empire State of Mind (2009)?','Rihanna','Alicia Keys','Beyoncé','Mary J. Blige','B',NULL);
INSERT INTO `questions` VALUES (193,39,'Jak brzmi prawdziwe imię i nazwisko Lil Wayne\'a?','Dwayne Williams','Dwayne Jackson','Dwayne Carter','Dwayne Brooks','C',NULL);
INSERT INTO `questions` VALUES (194,39,'Z jakiego miasta pochodzi Lil Wayne?','Atlanta','Nowy Orlean','Memphis','Houston','B',NULL);
INSERT INTO `questions` VALUES (195,39,'Z którą wytwórnią Lil Wayne był związany od nastoletnich lat?','Def Jam','No Limit Records','Roc-A-Fella Records','Cash Money Records','D',NULL);
INSERT INTO `questions` VALUES (196,39,'Jak nazywa się wytwórnia Lil Wayne\'a, która wydawała Drake\'a i Nicki Minaj?','OVO Sound','Young Money','Quality Control','G-Unit','B',NULL);
INSERT INTO `questions` VALUES (197,39,'Który przebój Lil Wayne\'a z 2008 roku nagrał ze Static Majorem?','Mrs. Officer','Lollipop','6 Foot 7 Foot','A Milli','B',NULL);
INSERT INTO `questions` VALUES (198,40,'Kto tworzył duet OutKast?','Eric B. i Rakim','Mos Def i Talib Kweli','André 3000 i Big Boi','Method Man i Redman','C',NULL);
INSERT INTO `questions` VALUES (199,40,'Z jakiego miasta pochodzi OutKast?','Houston','Memphis','Atlanta','Nowy Orlean','C',NULL);
INSERT INTO `questions` VALUES (200,40,'Który album OutKast zdobył w 2004 roku nagrodę Grammy za Album Roku?','Speakerboxxx/The Love Below','Stankonia','ATLiens','Aquemini','A',NULL);
INSERT INTO `questions` VALUES (201,40,'Jak nazywa się największy przebój OutKast z 2003 roku?','B.O.B.','Roses','Ms. Jackson','Hey Ya!','D',NULL);
INSERT INTO `questions` VALUES (202,40,'Który utwór OutKast z 2000 roku był przeprosinami skierowanymi do matki byłej partnerki?','Hey Ya!','Ms. Jackson','Roses','So Fresh, So Clean','B',NULL);
INSERT INTO `questions` VALUES (203,41,'Który raper używa przydomka Tunechi?','Young Thug','Gunna','Lil Wayne','Lil Baby','C',NULL);
INSERT INTO `questions` VALUES (204,41,'Kto na wspólnym albumie z Future\'em występuje jako „Baby Pluto”?','Lil Uzi Vert','Playboi Carti','Ken Carson','Trippie Redd','A',NULL);
INSERT INTO `questions` VALUES (205,41,'Jaki przydomek Kendricka Lamara z ery DAMN. nawiązuje do filmu Godziny szczytu 2?','King Kendrick','K.Dot','Compton Kenny','Kung Fu Kenny','D',NULL);
INSERT INTO `questions` VALUES (206,41,'Który przydomek Drake\'a nawiązuje do Toronto, nazywanego „The 6”?','Yeezy','6 God','Pluto','Makaveli','B',NULL);
INSERT INTO `questions` VALUES (207,41,'Który raper nosi przydomki Hov i Hova?','Nas','Kanye West','Jay-Z','Snoop Dogg','C',NULL);
INSERT INTO `questions` VALUES (208,42,'Jak nazywa się debiutancki album studyjny Drake\'a z 2010 roku?','Take Care','Thank Me Later','So Far Gone','Views','B',NULL);
INSERT INTO `questions` VALUES (209,42,'Jak nazywa się debiutancki album studyjny Travisa Scotta z 2015 roku?','Astroworld','Owl Pharaoh','Birds in the Trap Sing McKnight','Rodeo','D',NULL);
INSERT INTO `questions` VALUES (210,42,'Jak nazywa się debiutancki album studyjny Juice WRLD z 2018 roku?','Goodbye & Good Riddance','Death Race for Love','Legends Never Die','Fighting Demons','A',NULL);
INSERT INTO `questions` VALUES (211,42,'Jak nazywa się debiutancki album studyjny Lil Uzi Verta z 2017 roku?','Eternal Atake','Luv Is Rage','Luv Is Rage 2','Pink Tape','C',NULL);
INSERT INTO `questions` VALUES (212,42,'Jak nazywa się debiutancki album studyjny Future\'a z 2012 roku?','DS2','Pluto','Honest','HNDRXX','B',NULL);
INSERT INTO `questions` VALUES (213,43,'Jak brzmi prawdziwe imię i nazwisko Ice Cube\'a?','Andre Young','O\'Shea Jackson','Calvin Broadus','Curtis Jackson','B',NULL);
INSERT INTO `questions` VALUES (214,43,'Do którego filmu z 1995 roku Ice Cube współtworzył scenariusz i zagrał w nim główną rolę?','8 Mile','Barbershop','Friday','Straight Outta Compton','C',NULL);
INSERT INTO `questions` VALUES (215,43,'Jak nazywa się debiutancki solowy album Ice Cube\'a z 1990 roku?','AmeriKKKa\'s Most Wanted','Death Certificate','The Predator','Lethal Injection','A',NULL);
INSERT INTO `questions` VALUES (216,43,'W jakim filmie z 1991 roku Ice Cube zadebiutował jako aktor?','Friday','Menace II Society','Juice','Boyz n the Hood','D',NULL);
INSERT INTO `questions` VALUES (217,43,'Kto zagrał Ice Cube\'a w filmie Straight Outta Compton z 2015 roku?','Kevin Hart','Jego syn','Chris Tucker','Jego młodszy brat','B',NULL);
INSERT INTO `questions` VALUES (218,44,'Spór z którym członkiem N.W.A doprowadził w 1991 roku do odejścia Dr. Dre z grupy?','Eazy-E','Ice Cube','MC Ren','DJ Yella','A',NULL);
INSERT INTO `questions` VALUES (219,44,'Jak nazywa się debiutancki album studyjny N.W.A z 1988 roku?','Efil4zaggin','N.W.A. and the Posse','Straight Outta Compton','The Chronic','C',NULL);
INSERT INTO `questions` VALUES (220,44,'Który członek N.W.A założył wytwórnię Ruthless Records?','Dr. Dre','Ice Cube','MC Ren','Eazy-E','D',NULL);
INSERT INTO `questions` VALUES (221,44,'Który członek N.W.A odszedł z grupy w 1989 roku po sporach o pieniądze?','Dr. Dre','Ice Cube','Eazy-E','DJ Yella','B',NULL);
INSERT INTO `questions` VALUES (222,44,'W którym roku N.W.A zostali wprowadzeni do Rock and Roll Hall of Fame?','2008','2012','2016','2020','C',NULL);
INSERT INTO `questions` VALUES (223,45,'Do wytwórni którego artysty należy Destroy Lonely?','Travis Scott','Playboi Carti','Future','Lil Uzi Vert','B',NULL);
INSERT INTO `questions` VALUES (224,45,'Z jakim miastem związany jest Destroy Lonely?','Houston','Chicago','Atlanta','Nowy Jork','C',NULL);
INSERT INTO `questions` VALUES (225,45,'Jak nazywa się album Destroy Lonely\'ego z 2023 roku?','If Looks Could Kill','A Great Chaos','No Stylist','Love Lasts Forever','A',NULL);
INSERT INTO `questions` VALUES (226,45,'Który projekt Destroy Lonely\'ego z 2022 roku ma wiralowy utwór tytułowy?','X','Project X','If Looks Could Kill','No Stylist','D',NULL);
INSERT INTO `questions` VALUES (227,45,'Który raper należy do tej samej wytwórni co Destroy Lonely?','Trippie Redd','Ken Carson','Don Toliver','Lil Baby','B',NULL);
INSERT INTO `questions` VALUES (228,26,'Który raper wydał w 2021 roku album Punk?','Young Thug','Gunna','Lil Baby','Future','A',NULL);
INSERT INTO `questions` VALUES (229,26,'Jak nazywa się album Future\'a z 2022 roku z przebojem Wait For U?','HNDRXX','I Never Liked You','Pluto','DS2','B',NULL);
INSERT INTO `questions` VALUES (230,26,'Jak nazywa się album Lil Uzi Verta z 2023 roku?','Eternal Atake','Pink Tape','Luv Is Rage 2','Red & White','B',NULL);
INSERT INTO `questions` VALUES (231,26,'Jak nazywa się album Gunny z 2023 roku?','DS4EVER','WUNNA','Drip or Drown 2','a Gift & a Curse','D',NULL);
INSERT INTO `questions` VALUES (232,26,'Który raper wydał w 2024 roku album american dream?','Travis Scott','21 Savage','Drake','Future','B',NULL);
INSERT INTO `questions` VALUES (233,25,'Na jakiej platformie wypromowali się m.in. Juice WRLD, Trippie Redd i Lil Uzi Vert?','MySpace','Vine','SoundCloud','Bandcamp','C',NULL);
INSERT INTO `questions` VALUES (234,25,'Jak nazywa się album Tylera, The Creatora z 2017 roku?','Goblin','Wolf','Cherry Bomb','Flower Boy','D',NULL);
INSERT INTO `questions` VALUES (235,25,'Jak nazywa się wspólny projekt Lil Baby\'ego i Gunny z 2018 roku?','Drip Season','Drip Harder','Slime Language','Harder Than Ever','B',NULL);
INSERT INTO `questions` VALUES (236,25,'Jak nazywa się album Eminema z 2010 roku?','Revival','Recovery','Relapse','Kamikaze','B',NULL);
INSERT INTO `questions` VALUES (237,25,'Który raper wydał w 2011 roku album Tha Carter IV?','Young Thug','Kanye West','Lil Wayne','Drake','C',NULL);
INSERT INTO `questions` VALUES (238,24,'Jak nazywa się album Jay-Z wydany 11 września 2001 roku?','Reasonable Doubt','The Blueprint','Kingdom Come','The Black Album','B',NULL);
INSERT INTO `questions` VALUES (239,24,'Który album Eminema był najlepiej sprzedającym się albumem 2002 roku w USA?','The Slim Shady LP','Encore','The Eminem Show','The Marshall Mathers LP','C',NULL);
INSERT INTO `questions` VALUES (240,24,'Jak nazywa się album OutKast z 2000 roku?','Stankonia','ATLiens','Idlewild','Aquemini','A',NULL);
INSERT INTO `questions` VALUES (241,24,'Jak nazywa się mixtape Drake\'a z 2009 roku, który przyniósł mu kontrakt płytowy?','So Far Gone','Comeback Season','Thank Me Later','Take Care','A',NULL);
INSERT INTO `questions` VALUES (242,24,'Jak nazywa się album Nasa z 2002 roku?','Illmatic','Hip Hop Is Dead','Stillmatic','God\'s Son','D',NULL);
INSERT INTO `questions` VALUES (243,23,'Który album trafił na 1. miejsce Billboard 200, gdy jego autor przebywał w więzieniu?','Ready to Die','Me Against the World','Doggystyle','Reasonable Doubt','B',NULL);
INSERT INTO `questions` VALUES (244,23,'Który raper wydał w 1992 roku album The Predator?','Dr. Dre','Ice Cube','Snoop Dogg','2Pac','B',NULL);
INSERT INTO `questions` VALUES (245,23,'Który album Eminema z 1999 roku przyniósł mu międzynarodową sławę?','The Marshall Mathers LP','The Eminem Show','Infinite','The Slim Shady LP','D',NULL);
INSERT INTO `questions` VALUES (246,23,'Który raper zadebiutował w 1999 roku albumem Tha Block Is Hot?','Lil Wayne','Jay-Z','Nas','Snoop Dogg','A',NULL);
INSERT INTO `questions` VALUES (247,23,'Za który album Jay-Z otrzymał w 1999 roku nagrodę Grammy dla najlepszego albumu rapowego?','Vol. 2... Hard Knock Life','In My Lifetime, Vol. 1','The Blueprint','Reasonable Doubt','A',NULL);
INSERT INTO `questions` VALUES (248,41,'Który raper używa przydomka Pretty Flacko?','Playboi Carti','Tyler, The Creator','A$AP Rocky','Travis Scott','C',NULL);
INSERT INTO `questions` VALUES (249,41,'Pod jakim pseudonimem Snoop Dogg nagrał w 2013 roku album reggae?','Snoop Tiger','Snoop Lion','Snoop Marley','Bigg Boss','B',NULL);
INSERT INTO `questions` VALUES (250,41,'Który raper nosi przydomek La Flame?','Travis Scott','Trippie Redd','Kid Cudi','Don Toliver','A',NULL);
INSERT INTO `questions` VALUES (251,41,'Który raper używał przydomka Escobar?','Jay-Z','50 Cent','Snoop Dogg','Nas','D',NULL);
INSERT INTO `questions` VALUES (252,41,'Jak nazywa się postać, w którą Tyler, The Creator wcielił się na albumie z 2021 roku?','Slim Shady','Wolf Haley','Kung Fu Kenny','Tyler Baudelaire','D',NULL);
INSERT INTO `questions` VALUES (253,27,'Na którym utworze Future\'a i Metro Boomina Kendrick Lamar zaatakował Drake\'a?','Like That','Euphoria','Not Like Us','Type Shit','A',NULL);
INSERT INTO `questions` VALUES (254,27,'Jak nazywa się bit, który Metro Boomin wydał w 2024 roku, drwiąc z Drake\'a?','Like That','Family Matters','BBL Drizzy','Push Ups','C',NULL);
INSERT INTO `questions` VALUES (255,27,'W którym utworze z 1996 roku 2Pac zaatakował Nasa?','Toss It Up','Ambitionz Az a Ridah','California Love','Against All Odds','D',NULL);
INSERT INTO `questions` VALUES (256,27,'Z kim Young Thug popadł w 2015 roku w konflikt o tytuł swojego mixtape\'u?','Drake','Future','Lil Wayne','Kanye West','C',NULL);
INSERT INTO `questions` VALUES (257,27,'Którego rapera i producenta 2Pac zaatakował w utworze Toss It Up (1996)?','Snoop Dogg','Ice Cube','Eminem','Dr. Dre','D',NULL);
INSERT INTO `questions` VALUES (258,42,'Jak nazywa się debiutancki album studyjny 21 Savage z 2017 roku?','i am > i was','Savage Mode','Issa Album','american dream','C',NULL);
INSERT INTO `questions` VALUES (259,42,'Jak nazywa się debiutancki album studyjny Lil Baby\'ego z 2018 roku?','It\'s Only Me','Drip Harder','My Turn','Harder Than Ever','D',NULL);
INSERT INTO `questions` VALUES (260,42,'Jak nazywa się pierwszy album studyjny Kendricka Lamara, wydany niezależnie w 2011 roku?','Section.80','good kid, m.A.A.d city','Overly Dedicated','DAMN.','A',NULL);
INSERT INTO `questions` VALUES (261,42,'Jak nazywa się debiutancki album studyjny Migos z 2015 roku?','Yung Rich Nation','Culture','Culture II','No Label II','A',NULL);
INSERT INTO `questions` VALUES (262,42,'Jak nazywa się debiutancki album 2Paca z 1991 roku?','All Eyez on Me','Thug Life: Volume 1','2Pacalypse Now','Me Against the World','C',NULL);
INSERT INTO `questions` VALUES (263,28,'Z kim Travis Scott nagrał w 2020 roku utwór THE SCOTTS?','Kid Cudi','Don Toliver','Kanye West','Drake','A',NULL);
INSERT INTO `questions` VALUES (264,28,'Który raper gościnnie występuje w utworze Still D.R.E. Dr. Dre?','Ice Cube','Snoop Dogg','50 Cent','Eminem','B',NULL);
INSERT INTO `questions` VALUES (265,28,'Z kim A$AP Rocky nagrał w 2018 roku utwór Potato Salad?','Playboi Carti','Kendrick Lamar','Tyler, The Creator','Kid Cudi','C',NULL);
INSERT INTO `questions` VALUES (266,28,'Który utwór Drake\'a z trzema innymi raperami trafił do filmu o LeBronie Jamesie?','All of the Lights','Monster','Forever','Crack a Bottle','C',NULL);
INSERT INTO `questions` VALUES (267,28,'Który artysta gościnnie wystąpił w utworze CAN\'T SAY Travisa Scotta (2018)?','Kid Cudi','Drake','Young Thug','Don Toliver','D',NULL);
INSERT INTO `questions` VALUES (268,5,'Jak nazywa się album 21 Savage z 2018 roku?','The Slaughter Tape','american dream','i am > i was','Issa Album','C',NULL);
INSERT INTO `questions` VALUES (269,5,'Który aktor jest narratorem wspólnego albumu 21 Savage i Metro Boomina z 2020 roku?','Denzel Washington','Snoop Dogg','Morgan Freeman','Samuel L. Jackson','C',NULL);
INSERT INTO `questions` VALUES (270,5,'Z kim 21 Savage nagrał przebój rockstar (2017)?','Future','Travis Scott','Drake','Post Malone','D',NULL);
INSERT INTO `questions` VALUES (271,5,'Jaki tatuaż ma 21 Savage na czole?','Gwiazdę','Sztylet','Krzyż','Łzę','B',NULL);
INSERT INTO `questions` VALUES (272,5,'Z kim 21 Savage nagrał album Without Warning (2017)?','Young Thug i Gunna','Offset i Metro Boomin','Drake i Metro Boomin','Future i Metro Boomin','B',NULL);
INSERT INTO `questions` VALUES (273,29,'Który utwór 2Paca z 1995 roku jest hołdem dla jego matki?','Dear Mama','Changes','Brenda\'s Got a Baby','Keep Ya Head Up','A',NULL);
INSERT INTO `questions` VALUES (274,29,'W którym filmie z 1992 roku 2Pac zagrał rolę Bishopa?','Above the Rim','Boyz n the Hood','Juice','Poetic Justice','C',NULL);
INSERT INTO `questions` VALUES (275,29,'W jakiej grupie 2Pac zaczynał karierę jako tancerz i raper?','Digital Underground','Outlawz','N.W.A','Westside Connection','A',NULL);
INSERT INTO `questions` VALUES (276,29,'Który utwór 2Paca, wydany pośmiertnie w 1998 roku, porusza temat nierówności rasowych?','Dear Mama','California Love','Hit \'Em Up','Changes','D',NULL);
INSERT INTO `questions` VALUES (277,29,'Z kim 2Pac nagrał utwór 2 of Amerikaz Most Wanted?','Dr. Dre','Ice Cube','Snoop Dogg','Nas','C',NULL);
INSERT INTO `questions` VALUES (278,37,'Jak nazywa się drugi album 50 Centa z 2005 roku?','Animal Ambition','Curtis','Before I Self Destruct','The Massacre','D',NULL);
INSERT INTO `questions` VALUES (279,37,'Kto gościnnie wystąpił z 50 Centem w przeboju Candy Shop (2005)?','Olivia','Beyoncé','Alicia Keys','Rihanna','A',NULL);
INSERT INTO `questions` VALUES (280,37,'Który serial telewizyjny 50 Cent współtworzył jako producent wykonawczy?','Empire','The Wire','Snowfall','Power','D',NULL);
INSERT INTO `questions` VALUES (281,37,'Który raper podpisał 50 Centa w 2002 roku do swojej wytwórni?','Kanye West','Jay-Z','Snoop Dogg','Eminem','D',NULL);
INSERT INTO `questions` VALUES (282,37,'Na udziałach w której marce napojów 50 Cent zarobił fortunę w 2007 roku?','Red Bull','Gatorade','Monster','Vitaminwater','D',NULL);
INSERT INTO `questions` VALUES (283,1,'Jak nazywa się album A$AP Rocky\'ego z 2015 roku?','Live.Love.A$AP','At.Long.Last.A$AP','TESTING','Long.Live.A$AP','B',NULL);
INSERT INTO `questions` VALUES (284,1,'Jak nazywa się album A$AP Rocky\'ego z 2018 roku?','Cozy Tapes Vol. 2','TESTING','Long.Live.A$AP','At.Long.Last.A$AP','B',NULL);
INSERT INTO `questions` VALUES (285,1,'Z jaką piosenkarką A$AP Rocky jest w związku i ma dzieci?','Rihanna','SZA','Beyoncé','Nicki Minaj','A',NULL);
INSERT INTO `questions` VALUES (286,1,'W którym utworze A$AP Rocky\'ego z 2015 roku gościnnie pojawił się Rod Stewart?','Wild for the Night','Fine Whine','Everyday','L$D','C',NULL);
INSERT INTO `questions` VALUES (287,1,'Jak nazywał się współzałożyciel A$AP Mob, zmarły w 2015 roku?','A$AP Twelvyy','A$AP Nast','A$AP Ferg','A$AP Yams','D',NULL);
INSERT INTO `questions` VALUES (288,6,'Który utwór Chief Keefa z 2012 roku doczekał się remiksu z Kanye Westem?','Hate Bein\' Sober','I Don\'t Like','Faneto','3Hunna','B',NULL);
INSERT INTO `questions` VALUES (289,6,'Jak nazywa się kolektyw i wytwórnia Chief Keefa?','Glory Boyz Entertainment','Young Money','YSL','Opium','A',NULL);
INSERT INTO `questions` VALUES (290,6,'Z którą dużą wytwórnią Chief Keef podpisał kontrakt w 2012 roku?','Def Jam','Epic','Atlantic','Interscope','D',NULL);
INSERT INTO `questions` VALUES (291,6,'Jak nazywa się mixtape Chief Keefa z 2013 roku?','Nobody','Almighty So','Finally Rich','Back from the Dead','B',NULL);
INSERT INTO `questions` VALUES (292,6,'Ile lat miał Chief Keef, gdy w grudniu 2012 roku wydał swój debiutancki album?','15','21','17','19','C',NULL);
INSERT INTO `questions` VALUES (293,45,'Jak nazywa się wytwórnia, w której nagrywa Destroy Lonely?','Opium','YSL','Quality Control','Cactus Jack','A',NULL);
INSERT INTO `questions` VALUES (294,45,'Jak nazywa się album Destroy Lonely\'ego z 2024 roku?','If Looks Could Kill','Love Lasts Forever','No Stylist','A Great Chaos','B',NULL);
INSERT INTO `questions` VALUES (295,45,'Ojciec Destroy Lonely\'ego, raper I-20, był związany z wytwórnią którego rapera?','Lil Wayne','Ludacris','Jay-Z','Snoop Dogg','B',NULL);
INSERT INTO `questions` VALUES (296,45,'Z jakim nurtem trapu kojarzony jest Destroy Lonely?','Boom bap','Rage','Drill','G-funk','B',NULL);
INSERT INTO `questions` VALUES (297,45,'Jak brzmi prawdziwe imię i nazwisko Destroy Lonely\'ego?','Bobby Williams','Bobby Sandimanie','Bobby Carter','Bobby Jackson','B',NULL);
INSERT INTO `questions` VALUES (298,7,'Jak nazywa się debiutancki album studyjny Dona Tolivera z 2020 roku?','Love Sick','Donny Womack','Hardstone Psycho','Heaven or Hell','D',NULL);
INSERT INTO `questions` VALUES (299,7,'Z kim Don Toliver nagrał utwór Private Landing (2023)?','Justin Bieber i Future','Drake i 21 Savage','SZA i Future','Kid Cudi i Lil Baby','A',NULL);
INSERT INTO `questions` VALUES (300,7,'Kto gościnnie wystąpił w utworze 4 Me Dona Tolivera (2023)?','SZA','Kali Uchis','Rihanna','Doja Cat','B',NULL);
INSERT INTO `questions` VALUES (301,7,'Na jakim wspólnym albumie wytwórni Cactus Jack z 2019 roku pojawił się Don Toliver?','JACKBOYS','Astroworld','Rodeo','Heaven or Hell','A',NULL);
INSERT INTO `questions` VALUES (302,7,'Na czyim utworze Lemonade (2020) Don Toliver wystąpił razem z Gunną i NAV-em?','Metro Boomin','Travis Scott','Future','Internet Money','D',NULL);
INSERT INTO `questions` VALUES (303,32,'Komu Dr. Dre i Jimmy Iovine sprzedali w 2014 roku swoją firmę słuchawkową?','Apple','Google','Samsung','Sony','A',NULL);
INSERT INTO `questions` VALUES (304,32,'Czyjego albumu good kid, m.A.A.d city (2012) Dr. Dre był producentem wykonawczym?','Kid Cudi','Travis Scott','Kendrick Lamar','Drake','C',NULL);
INSERT INTO `questions` VALUES (305,32,'Jak nazywa się album Dr. Dre z 2015 roku inspirowany filmem o jego dawnej grupie?','2001','Detox','Compton','The Chronic','C',NULL);
INSERT INTO `questions` VALUES (306,32,'Z kim Dr. Dre współzałożył wytwórnię Death Row Records?','Ice Cube','Eazy-E','Suge Knight','Snoop Dogg','C',NULL);
INSERT INTO `questions` VALUES (307,32,'W którym roku Dr. Dre poprowadził występ w przerwie Super Bowl?','2025','2016','2022','2019','C',NULL);
INSERT INTO `questions` VALUES (308,8,'W teledysku do którego utworu z 2018 roku Drake rozdawał pieniądze ludziom w Miami?','God\'s Plan','Nice for What','Hotline Bling','In My Feelings','A',NULL);
INSERT INTO `questions` VALUES (309,8,'Który utwór był pierwszym numerem 1 Drake\'a jako głównego wykonawcy na Hot 100?','Controlla','Hold On, We\'re Going Home','One Dance','Hotline Bling','C',NULL);
INSERT INTO `questions` VALUES (310,8,'Na okładce którego albumu z 2016 roku Drake siedzi na szczycie wieży CN Tower?','Views','Take Care','Nothing Was the Same','Scorpion','A',NULL);
INSERT INTO `questions` VALUES (311,8,'Jak nazywa się album Drake\'a z 2022 roku, utrzymany w stylistyce house i dance?','For All the Dogs','Honestly, Nevermind','Certified Lover Boy','Scorpion','B',NULL);
INSERT INTO `questions` VALUES (312,8,'Jak nazywa się album Drake\'a z 2013 roku?','Nothing Was the Same','Take Care','Views','Thank Me Later','A',NULL);
INSERT INTO `questions` VALUES (313,36,'Jak nazywa się grupa, której członkiem był Eminem?','D12','N.W.A','Slaughterhouse','G-Unit','A',NULL);
INSERT INTO `questions` VALUES (314,36,'Jak nazywa się wytwórnia założona przez Eminema?','Young Money','Aftermath','G-Unit Records','Shady Records','D',NULL);
INSERT INTO `questions` VALUES (315,36,'Który utwór Eminema z 2000 roku opowiada historię obsesyjnego fana?','Mockingbird','Without Me','The Real Slim Shady','Stan','D',NULL);
INSERT INTO `questions` VALUES (316,36,'Z kim Eminem nagrał utwór The Monster (2013)?','Beyoncé','Ed Sheeran','Rihanna','Dido','C',NULL);
INSERT INTO `questions` VALUES (317,36,'Jak nazywa się album Eminema z 2018 roku, wydany bez zapowiedzi?','Revival','Music to Be Murdered By','Recovery','Kamikaze','D',NULL);
INSERT INTO `questions` VALUES (318,2,'Który producent z kolektywu Dungeon Family był kuzynem Future\'a?','Metro Boomin','Southside','Rico Wade','Zaytoven','C',NULL);
INSERT INTO `questions` VALUES (319,2,'Który album Future wydał w 2017 roku tydzień po albumie FUTURE?','EVOL','I Never Liked You','HNDRXX','The WIZRD','C',NULL);
INSERT INTO `questions` VALUES (320,2,'Z kim Future nagrał wspólny album Super Slimey (2017)?','Lil Uzi Vert','Drake','Young Thug','Gunna','C',NULL);
INSERT INTO `questions` VALUES (321,2,'Jak nazywa się album Future\'a z 2019 roku?','EVOL','Honest','The WIZRD','HNDRXX','C',NULL);
INSERT INTO `questions` VALUES (322,2,'Z którym producentem Future nagrał mixtape Beast Mode (2015)?','Zaytoven','Metro Boomin','Southside','Mike WiLL Made-It','A',NULL);
INSERT INTO `questions` VALUES (323,9,'Jak nazywa się seria mixtape\'ów Gunny?','Slime Season','Drip Season','Beast Mode','Savage Mode','B',NULL);
INSERT INTO `questions` VALUES (324,9,'Jak nazywa się debiutancki album studyjny Gunny z 2019 roku?','One of Wun','Drip or Drown 2','WUNNA','DS4EVER','B',NULL);
INSERT INTO `questions` VALUES (325,9,'Do której wytwórni Younga Thuga należał Gunna?','YSL','Opium','Cactus Jack','Quality Control','A',NULL);
INSERT INTO `questions` VALUES (326,9,'Który solowy utwór Gunny z 2023 roku dotarł do pierwszej piątki listy Billboard Hot 100?','Lemonade','fukumean','pushin P','Drip Too Hard','B',NULL);
INSERT INTO `questions` VALUES (327,9,'Jak nazywa się album Gunny z 2024 roku?','DS4EVER','WUNNA','a Gift & a Curse','One of Wun','D',NULL);
INSERT INTO `questions` VALUES (328,43,'Który utwór Ice Cube\'a z 1992 roku opisuje spokojny, udany dzień w Los Angeles?','You Can Do It','Check Yo Self','No Vaseline','It Was a Good Day','D',NULL);
INSERT INTO `questions` VALUES (329,43,'W jakiej serii komediowej Ice Cube grał razem z Kevinem Hartem?','Ride Along (Wspólny kurs)','Barbershop','Friday','Are We There Yet?','A',NULL);
INSERT INTO `questions` VALUES (330,43,'Jak nazywa się liga koszykówki 3 na 3, którą współzałożył Ice Cube?','NBA G League','BIG3','EYBL','AND1','B',NULL);
INSERT INTO `questions` VALUES (331,43,'Jak nazywa się grupa, którą Ice Cube stworzył z WC i Mackiem 10?','Cypress Hill','Tha Dogg Pound','N.W.A','Westside Connection','D',NULL);
INSERT INTO `questions` VALUES (332,43,'Jak nazywa się drugi solowy album Ice Cube\'a z 1991 roku?','Death Certificate','Lethal Injection','The Predator','AmeriKKKa\'s Most Wanted','A',NULL);
INSERT INTO `questions` VALUES (333,38,'Z jaką piosenkarką Jay-Z jest w związku małżeńskim od 2008 roku?','Alicia Keys','Rihanna','Mary J. Blige','Beyoncé','D',NULL);
INSERT INTO `questions` VALUES (334,38,'Jak nazywa się firma muzyczno-rozrywkowa założona przez Jay-Z w 2008 roku?','Roc Nation','Roc-A-Fella Records','G.O.O.D. Music','Def Jam','A',NULL);
INSERT INTO `questions` VALUES (335,38,'Jaką funkcję pełnił Jay-Z w wytwórni Def Jam w latach 2004–2007?','Rzecznika prasowego','Menedżera trasy','Prezesa','Głównego producenta','C',NULL);
INSERT INTO `questions` VALUES (336,38,'Jaki serwis streamingowy kupił Jay-Z w 2015 roku?','SoundCloud','Tidal','Spotify','Deezer','B',NULL);
INSERT INTO `questions` VALUES (337,38,'Jak nazywa się album Jay-Z z 2017 roku?','The Black Album','Magna Carta Holy Grail','Kingdom Come','4:44','D',NULL);
INSERT INTO `questions` VALUES (338,10,'Jak nazywa się drugi album studyjny Juice WRLD z 2019 roku?','Death Race for Love','Goodbye & Good Riddance','Fighting Demons','Legends Never Die','A',NULL);
INSERT INTO `questions` VALUES (339,10,'Jaką liczbą posługiwał się Juice WRLD jako symbolem zamieniania zła w dobro?','999','777','444','666','A',NULL);
INSERT INTO `questions` VALUES (340,10,'Z jaką wytwórnią, obok Interscope, związany był Juice WRLD?','Young Money','Opium','Cactus Jack','Grade A Productions','D',NULL);
INSERT INTO `questions` VALUES (341,10,'Jak nazywa się pośmiertny album Juice WRLD z 2021 roku?','Fighting Demons','The Party Never Ends','Legends Never Die','Death Race for Love','A',NULL);
INSERT INTO `questions` VALUES (342,10,'Który utwór był pierwszym singlem z debiutanckiego albumu Juice WRLD?','Righteous','All Girls Are the Same','Wishing Well','Robbery','B',NULL);
INSERT INTO `questions` VALUES (343,11,'Jak nazywa się album Kanye Westa z 2008 roku, na którym intensywnie używał Auto-Tune?','Graduation','Late Registration','Yeezus','808s & Heartbreak','D',NULL);
INSERT INTO `questions` VALUES (344,11,'Jak nazywa się album Kanye Westa z 2013 roku?','Yeezus','Donda','Graduation','The Life of Pablo','A',NULL);
INSERT INTO `questions` VALUES (345,11,'Który przebój Kanye Westa z 2005 roku nagrał z Jamiem Foxxem?','Touch the Sky','Heartless','Power','Gold Digger','D',NULL);
INSERT INTO `questions` VALUES (346,11,'Z którą marką Kanye West wypuścił w 2015 roku buty Yeezy Boost?','Puma','Nike','Adidas','Reebok','C',NULL);
INSERT INTO `questions` VALUES (347,11,'Który utwór Kanye Westa z 2007 roku wykorzystuje sampel z utworu Daft Punk?','Heartless','Power','Flashing Lights','Stronger','D',NULL);
INSERT INTO `questions` VALUES (348,12,'W którym roku Ken Carson podpisał kontrakt z wytwórnią Playboi Cartiego?','2016','2021','2023','2019','D',NULL);
INSERT INTO `questions` VALUES (349,12,'Jaki dzień Ken Carson wybrał na premierę albumu More Chaos (2025)?','Rocznicę swojego debiutu','Swoje 25. urodziny','Sylwestra','Halloween','B',NULL);
INSERT INTO `questions` VALUES (350,12,'Pod jakim pseudonimem występował Ken Carson na początku kariery?','Young Ken','Kenny X','Teen X','Lil Carson','C',NULL);
INSERT INTO `questions` VALUES (351,12,'Jak brzmi prawdziwe imię i nazwisko Kena Carsona?','Kenyatta Frazier','Kenny Carter','Kenneth Carson','Kendrick Frazier','A',NULL);
INSERT INTO `questions` VALUES (352,12,'Która duża wytwórnia współwydaje albumy Kena Carsona?','Def Jam','Interscope','Atlantic','Columbia','B',NULL);
INSERT INTO `questions` VALUES (353,13,'Jak nazywa się album Kendricka Lamara z 2022 roku?','untitled unmastered.','Mr. Morale & the Big Steppers','DAMN.','GNX','B',NULL);
INSERT INTO `questions` VALUES (354,13,'Jak nazywa się firma kreatywna założona przez Kendricka Lamara i Dave\'a Free\'a?','AWGE','Cactus Jack','pgLang','OVO','C',NULL);
INSERT INTO `questions` VALUES (355,13,'Który utwór był pierwszym numerem 1 Kendricka Lamara jako głównego wykonawcy na Hot 100?','DNA.','Swimming Pools (Drank)','LOYALTY.','HUMBLE.','D',NULL);
INSERT INTO `questions` VALUES (356,13,'Który utwór Kendricka Lamara stał się hymnem ruchu Black Lives Matter?','Alright','King Kunta','i','The Blacker the Berry','A',NULL);
INSERT INTO `questions` VALUES (357,13,'Jak nazywa się grupa Kendricka Lamara, ScHoolboya Q, Ab-Soula i Jaya Rocka?','Black Hippy','Odd Future','Pro Era','A$AP Mob','A',NULL);
INSERT INTO `questions` VALUES (358,14,'Jak nazywa się animowany projekt Kid Cudiego z 2022 roku na Netflixie?','Entergalactic','Arcane','Invincible','Blue Eye Samurai','A',NULL);
INSERT INTO `questions` VALUES (359,14,'Kto gościnnie wystąpił w utworze Pursuit of Happiness Kid Cudiego?','Coldplay','Gorillaz','MGMT i Ratatat','Daft Punk','C',NULL);
INSERT INTO `questions` VALUES (360,14,'Jak nazywa się zespół rockowy, który Kid Cudi założył z Dot da Geniusem?','WZRD','Gorillaz','D12','N.E.R.D','A',NULL);
INSERT INTO `questions` VALUES (361,14,'W jakim serialu HBO z lat 2010–2011 występował Kid Cudi?','Euphoria','How to Make It in America','Westworld','Entourage','B',NULL);
INSERT INTO `questions` VALUES (362,14,'Jak nazywa się własna wytwórnia Kid Cudiego?','Cactus Jack','Opium','OVO Sound','Wicked Awesome','D',NULL);
INSERT INTO `questions` VALUES (363,15,'Jak nazywa się album Lil Baby\'ego z 2022 roku?','My Turn','Harder Than Ever','Drip Harder','It\'s Only Me','D',NULL);
INSERT INTO `questions` VALUES (364,15,'Z kim Lil Baby nagrał przebój We Paid (2020)?','Future','Gunna','Young Thug','42 Dugg','D',NULL);
INSERT INTO `questions` VALUES (365,15,'Z kim Lil Baby nagrał utwór Yes Indeed (2018)?','Future','Drake','21 Savage','Travis Scott','B',NULL);
INSERT INTO `questions` VALUES (366,15,'Jak nazywała się wytwórnia założona przez Lil Baby\'ego w 2017 roku?','OVO Sound','YSL','Opium','4PF','D',NULL);
INSERT INTO `questions` VALUES (367,15,'Jak nazywa się album Lil Baby\'ego z 2025 roku?','Street Gossip','My Turn','WHAM','It\'s Only Me','C',NULL);
INSERT INTO `questions` VALUES (368,3,'Który utwór Lil Uzi Verta z 2022 roku stał się wiralem dzięki brzmieniu Jersey club?','Money Longer','XO TOUR Llif3','20 Min','Just Wanna Rock','D',NULL);
INSERT INTO `questions` VALUES (369,3,'Jak nazywa się mixtape Lil Uzi Verta z 2015 roku?','Luv Is Rage 2','Eternal Atake','Luv Is Rage','Pink Tape','C',NULL);
INSERT INTO `questions` VALUES (370,3,'Z którą wytwórnią, prowadzoną przez DJ Dramę i Dona Cannona, związany był Lil Uzi Vert?','YSL','Generation Now','Opium','Quality Control','B',NULL);
INSERT INTO `questions` VALUES (371,3,'Z kim Lil Uzi Vert nagrał utwór Aye (2023)?','Playboi Carti','Future','Young Thug','Travis Scott','D',NULL);
INSERT INTO `questions` VALUES (372,3,'Na ścieżce dźwiękowej którego filmu z 2017 roku jest utwór Go Off?','Spider-Man: Homecoming','Szybcy i wściekli 8','Czarna Pantera','Venom','B',NULL);
INSERT INTO `questions` VALUES (373,39,'W jakiej grupie Lil Wayne zaczynał razem z Juvenile\'em, B.G. i Turkiem?','Young Money','Hot Boys','D12','G-Unit','B',NULL);
INSERT INTO `questions` VALUES (374,39,'Jak nazywa się mixtape Lil Wayne\'a z 2009 roku?','Sorry 4 the Wait','Dedication 2','Da Drought 3','No Ceilings','D',NULL);
INSERT INTO `questions` VALUES (375,39,'Który utwór Lil Wayne\'a z 2008 roku zdobył Grammy za najlepszy solowy występ rapowy?','Lollipop','Mrs. Officer','A Milli','6 Foot 7 Foot','C',NULL);
INSERT INTO `questions` VALUES (376,39,'Jak nazywa się rockowy album Lil Wayne\'a z 2010 roku?','Rebirth','Funeral','I Am Not a Human Being','Tha Carter V','A',NULL);
INSERT INTO `questions` VALUES (377,39,'Jak nazywa się album Lil Wayne\'a z 2018 roku, wydany po wieloletnim sporze z Birdmanem?','Tha Carter V','Funeral','Tha Carter IV','Rebirth','A',NULL);
INSERT INTO `questions` VALUES (378,16,'Z którym raperem Metro Boomin wydał w 2024 roku dwa wspólne albumy?','Future','Travis Scott','Young Thug','21 Savage','A',NULL);
INSERT INTO `questions` VALUES (379,16,'Który wokalista wystąpił z 21 Savage w utworze Creepin\' Metro Boomina (2022)?','Don Toliver','The Weeknd','Travis Scott','Drake','B',NULL);
INSERT INTO `questions` VALUES (380,16,'Który z tych przebojów wyprodukował Metro Boomin?','In da Club','Hotline Bling','Mask Off','Lollipop','C',NULL);
INSERT INTO `questions` VALUES (381,16,'Z którym raperem Metro Boomin nagrał album Double or Nothing (2017)?','Offset','Big Sean','Future','21 Savage','B',NULL);
INSERT INTO `questions` VALUES (382,16,'Kto gościnnie wystąpił w utworze Space Cadet Metro Boomina?','Lil Baby','Travis Scott','Gunna','Young Thug','C',NULL);
INSERT INTO `questions` VALUES (383,17,'Jak nazywa się album Migos z 2018 roku?','Culture','Culture III','Yung Rich Nation','Culture II','D',NULL);
INSERT INTO `questions` VALUES (384,17,'Jakie pokrewieństwo łączyło Quavo i Takeoffa?','Nie byli spokrewnieni','Quavo był wujkiem Takeoffa','Byli kuzynami','Byli braćmi','B',NULL);
INSERT INTO `questions` VALUES (385,17,'Z którą raperką ożenił się Offset?','Nicki Minaj','Latto','Cardi B','Megan Thee Stallion','C',NULL);
INSERT INTO `questions` VALUES (386,17,'Kto gościnnie wystąpił w utworze Walk It Talk It Migos (2018)?','Future','Travis Scott','Drake','Lil Uzi Vert','C',NULL);
INSERT INTO `questions` VALUES (387,17,'Z którą wytwórnią związani byli Migos?','Quality Control','YSL','Cash Money','Young Money','A',NULL);
INSERT INTO `questions` VALUES (388,44,'Jak nazywa się drugi album studyjny N.W.A z 1991 roku?','Efil4zaggin','The Chronic','Straight Outta Compton','100 Miles and Runnin\'','A',NULL);
INSERT INTO `questions` VALUES (389,44,'Jak nazywa się film biograficzny o N.W.A z 2015 roku?','Straight Outta Compton','All Eyez on Me','Notorious','8 Mile','A',NULL);
INSERT INTO `questions` VALUES (390,44,'Który członek N.W.A był DJ-em grupy?','MC Ren','Eazy-E','DJ Yella','Ice Cube','C',NULL);
INSERT INTO `questions` VALUES (391,44,'Który członek N.W.A zmarł w 1995 roku?','DJ Yella','MC Ren','Eazy-E','Dr. Dre','C',NULL);
INSERT INTO `questions` VALUES (392,44,'Który członek N.W.A zrobił największą karierę aktorską?','Dr. Dre','Ice Cube','Eazy-E','MC Ren','B',NULL);
INSERT INTO `questions` VALUES (393,31,'Z którym producentem Nas nagrał w latach 2020–2023 serię albumów?','Metro Boomin','Hit-Boy','DJ Premier','Kanye West','B',NULL);
INSERT INTO `questions` VALUES (394,31,'Jak nazywa się album Nasa z 2006 roku o prowokacyjnym tytule?','Stillmatic','Magic','Hip Hop Is Dead','King\'s Disease','C',NULL);
INSERT INTO `questions` VALUES (395,31,'Z którym producentem Nas wydał w 2025 roku wspólny album Light-Years?','Pharrell','Dr. Dre','DJ Premier','Hit-Boy','C',NULL);
INSERT INTO `questions` VALUES (396,31,'Który utwór rozpoczyna album Illmatic zaraz po intro?','N.Y. State of Mind','It Ain\'t Hard to Tell','Halftime','The World Is Yours','A',NULL);
INSERT INTO `questions` VALUES (397,31,'Z jaką supergrupą Nas nagrał w 1997 roku album razem z AZ, Foxy Brown i Nature?','Junior M.A.F.I.A.','The Firm','Mobb Deep','Westside Connection','B',NULL);
INSERT INTO `questions` VALUES (398,40,'Jak nazywa się drugi album OutKast z 1996 roku?','Aquemini','Southernplayalisticadillacmuzik','ATLiens','Stankonia','C',NULL);
INSERT INTO `questions` VALUES (399,40,'Jak nazywa się film muzyczny z 2006 roku, w którym zagrali członkowie OutKast?','Idlewild','ATL','Hustle & Flow','8 Mile','A',NULL);
INSERT INTO `questions` VALUES (400,40,'Na którym albumie z 2023 roku André 3000 gra na flecie?','New Blue Sun','Boomiverse','Speakerboxxx','The Love Below','A',NULL);
INSERT INTO `questions` VALUES (401,40,'Jak nazywa się solowy album Big Boia z 2010 roku?','Sir Lucious Left Foot: The Son of Chico Dusty','Speakerboxxx','Big Grams','Boomiverse','A',NULL);
INSERT INTO `questions` VALUES (402,40,'Jak rozwija się skrót w tytule utworu OutKast B.O.B.?','Beats On Bass','Bounce Or Break','Bombs Over Baghdad','Boys Over Broadway','C',NULL);
INSERT INTO `questions` VALUES (403,4,'Jak nazywa się wytwórnia założona przez Playboi Cartiego?','Cactus Jack','Opium','AWGE','YSL','B',NULL);
INSERT INTO `questions` VALUES (404,4,'Który producent stał za wczesnymi przebojami Playboi Cartiego?','Pi\'erre Bourne','Southside','Metro Boomin','Zaytoven','A',NULL);
INSERT INTO `questions` VALUES (405,4,'Z kim Playboi Carti nagrał utwór wokeuplikethis* (2017)?','Lil Uzi Vert','Future','Young Thug','Travis Scott','A',NULL);
INSERT INTO `questions` VALUES (406,4,'Który utwór z 2017 roku stał się pierwszym dużym przebojem Playboi Cartiego?','Shoota','Long Time','Sky','Magnolia','D',NULL);
INSERT INTO `questions` VALUES (407,4,'Kto gościnnie wystąpił w utworze Poke It Out Playboi Cartiego (2018)?','Travis Scott','Cardi B','Lil Uzi Vert','Nicki Minaj','D',NULL);
INSERT INTO `questions` VALUES (408,18,'Który utwór Popa Smoke\'a z 2019 roku przyniósł mu popularność?','Mood Swings','Dior','For the Night','Welcome to the Party','D',NULL);
INSERT INTO `questions` VALUES (409,18,'Jak nazywa się seria mixtape\'ów Popa Smoke\'a?','Savage Mode','Slime Season','Drip Season','Meet the Woo','D',NULL);
INSERT INTO `questions` VALUES (410,18,'Który utwór Popa Smoke\'a często puszczano podczas protestów w 2020 roku?','Mood Swings','Welcome to the Party','Dior','Gatti','C',NULL);
INSERT INTO `questions` VALUES (411,18,'Z kim Pop Smoke nagrał utwór For the Night (2020)?','Roddy Ricch i Quavo','Travis Scott i Quavo','Lil Baby i DaBaby','Drake i Future','C',NULL);
INSERT INTO `questions` VALUES (412,18,'Który brytyjski producent współtworzył charakterystyczne brzmienie Popa Smoke\'a?','Zaytoven','Metro Boomin','Pi\'erre Bourne','808Melo','D',NULL);
INSERT INTO `questions` VALUES (413,33,'Z jaką znaną prezenterką kulinarną Snoop Dogg prowadził program telewizyjny?','Oprah Winfrey','Gordon Ramsay','Martha Stewart','Ellen DeGeneres','C',NULL);
INSERT INTO `questions` VALUES (414,33,'Podczas jakiego wydarzenia w 2024 roku Snoop Dogg był korespondentem NBC?','Wimbledonu','Mundialu w Katarze','Igrzysk olimpijskich w Paryżu','Super Bowl','C',NULL);
INSERT INTO `questions` VALUES (415,33,'Który przebój z 1994 roku pochodzi z debiutanckiego albumu Snoop Dogga?','Young, Wild & Free','Sensual Seduction','Drop It Like It\'s Hot','Gin and Juice','D',NULL);
INSERT INTO `questions` VALUES (416,33,'Który przebój Snoop Dogga i Wiza Khalify z Bruno Marsem ukazał się w 2011 roku?','Young, Wild & Free','Gin and Juice','Drop It Like It\'s Hot','Beautiful','A',NULL);
INSERT INTO `questions` VALUES (417,33,'Prawa do której legendarnej wytwórni kupił Snoop Dogg w 2022 roku?','Def Jam','No Limit Records','Death Row Records','Aftermath','C',NULL);
INSERT INTO `questions` VALUES (418,30,'Który singiel Notorious B.I.G. opowiada o drodze od biedy do sukcesu?','Big Poppa','Hypnotize','Juicy','Mo Money Mo Problems','C',NULL);
INSERT INTO `questions` VALUES (419,30,'Który z tych utworów Notorious B.I.G. dotarł na 1. miejsce listy Billboard Hot 100?','Juicy','Hypnotize','One More Chance','Big Poppa','B',NULL);
INSERT INTO `questions` VALUES (420,30,'Z którą piosenkarką był żonaty Notorious B.I.G.?','Mary J. Blige','Faith Evans','Lil\' Kim','Aaliyah','B',NULL);
INSERT INTO `questions` VALUES (421,30,'Jaką grupę z Lil\' Kim w składzie wypromował Notorious B.I.G.?','Junior M.A.F.I.A.','Mobb Deep','Outlawz','The Firm','A',NULL);
INSERT INTO `questions` VALUES (422,30,'Który raper zagrał Notorious B.I.G. w filmie biograficznym z 2009 roku?','Jamal Woolard','Anthony Mackie','Derek Luke','Corey Hawkins','A',NULL);
INSERT INTO `questions` VALUES (423,19,'Jak nazywa się album Travisa Scotta z 2016 roku?','Birds in the Trap Sing McKnight','Astroworld','Utopia','Rodeo','A',NULL);
INSERT INTO `questions` VALUES (424,19,'W jakiej grze komputerowej Travis Scott dał w 2020 roku wirtualny koncert?','GTA Online','Fortnite','Minecraft','Roblox','B',NULL);
INSERT INTO `questions` VALUES (425,19,'Z jaką siecią restauracji Travis Scott stworzył w 2020 roku zestaw nazwany swoim imieniem?','KFC','Burger King','Wendy\'s','McDonald\'s','D',NULL);
INSERT INTO `questions` VALUES (426,19,'Z kim Travis Scott nagrał wspólny album Huncho Jack, Jack Huncho (2017)?','Young Thug','Takeoff','Offset','Quavo','D',NULL);
INSERT INTO `questions` VALUES (427,19,'Który singiel z albumu Rodeo dotarł najwyżej na liście Billboard Hot 100?','90210','3500','Oh My Dis Side','Antidote','D',NULL);
INSERT INTO `questions` VALUES (428,20,'Jak nazywa się seria mixtape\'ów Trippie Redda zapoczątkowana w 2017 roku?','A Love Letter to You','Slime Season','Drip Season','Meet the Woo','A',NULL);
INSERT INTO `questions` VALUES (429,20,'Jak nazywa się album Trippie Redda z 2019 roku?','Trip at Knight','Pegasus','!','Mansion Musik','C',NULL);
INSERT INTO `questions` VALUES (430,20,'Jak nazywa się album Trippie Redda z 2021 roku?','!','Trip at Knight','Life\'s a Trip','Pegasus','B',NULL);
INSERT INTO `questions` VALUES (431,20,'Który utwór Trippie Redda z 2017 roku stał się jego przełomowym przebojem?','Dark Knight Dummo','Love Scars','Topanga','Taking a Walk','B',NULL);
INSERT INTO `questions` VALUES (432,20,'Z kim Trippie Redd nagrał utwór Miss the Rage (2021)?','Ken Carson','Playboi Carti','Juice WRLD','Lil Uzi Vert','B',NULL);
INSERT INTO `questions` VALUES (433,21,'Jak nazywa się album Tylera, The Creatora z 2011 roku?','Flower Boy','Wolf','Cherry Bomb','Goblin','D',NULL);
INSERT INTO `questions` VALUES (434,21,'Jak nazywa się marka odzieżowa Tylera, The Creatora?','OVO','Golf Wang','Yeezy','Cactus Jack','B',NULL);
INSERT INTO `questions` VALUES (435,21,'Jak nazywa się festiwal muzyczny organizowany przez Tylera, The Creatora?','Camp Flog Gnaw','Rolling Loud','Lyrical Lemonade Summer Smash','Astroworld','A',NULL);
INSERT INTO `questions` VALUES (436,21,'Który singiel Tylera, The Creatora z 2019 roku dotarł do 13. miejsca Hot 100?','Who Dat Boy','EARFQUAKE','See You Again','Yonkers','B',NULL);
INSERT INTO `questions` VALUES (437,21,'Który utwór z 2011 roku, wraz z głośnym teledyskiem, przyniósł Tylerowi rozgłos?','Yonkers','Who Dat Boy','She','Tamale','A',NULL);
INSERT INTO `questions` VALUES (438,22,'Z kim Young Thug nagrał utwór The London (2019)?','Drake i Future','Gunna i Lil Baby','J. Cole i Travis Scott','Lil Uzi Vert i Playboi Carti','C',NULL);
INSERT INTO `questions` VALUES (439,22,'Z którą piosenkarką Young Thug nagrał przebój Havana (2017)?','Rihanna','Ariana Grande','Camila Cabello','Dua Lipa','C',NULL);
INSERT INTO `questions` VALUES (440,22,'Jak nazywa się seria mixtape\'ów Younga Thuga z lat 2015–2016?','Drip Season','Slime Season','Meet the Woo','Beast Mode','B',NULL);
INSERT INTO `questions` VALUES (441,22,'Co Young Thug miał na sobie na okładce swojego mixtape\'u z 2016 roku?','Garnitur','Sukienkę','Zbroję','Piżamę','B',NULL);
INSERT INTO `questions` VALUES (442,22,'Jak nazywa się album Younga Thuga z 2023 roku?','So Much Fun','Slime Language 2','Punk','Business Is Business','D',NULL);
INSERT INTO `questions` VALUES (443,46,'Który przydomek Yeata nawiązuje do marki zabawkowych ciężarówek?','Twizzy King','Big Krank','Rage Lord','King Tonka','D',NULL);
INSERT INTO `questions` VALUES (444,46,'Jaki dźwięk stał się znakiem rozpoznawczym utworów Yeata?','Dzwonki','Saksofon','Syreny','Skrzypce','A',NULL);
INSERT INTO `questions` VALUES (445,46,'Który album Yeata jako pierwszy zadebiutował na 1. miejscu Billboard 200?','Afterlyfe','2 Alive','Lyfestyle','2093','C',NULL);
INSERT INTO `questions` VALUES (446,46,'Który album Yeata z 2024 roku zainspirowała powieść „Rok 1984”?','Afterlyfe','Up 2 Me','2 Alive','2093','D',NULL);
INSERT INTO `questions` VALUES (447,46,'W którym roku Yeat wydał swój debiutancki album studyjny Up 2 Me?','2019','2020','2021','2022','C',NULL);
INSERT INTO `questions` VALUES (448,46,'Który utwór Yeata z 2022 roku pojawił się w zwiastunie filmu „Minionki: Wejście Gru”?','Rich Minion','Still Countin','Talk','Poppin','A',NULL);
INSERT INTO `questions` VALUES (449,46,'Które utwory Yeata stały się viralami na TikToku w 2021 roku?','Poppin i Talk','Still Countin i Turban','Flawlëss i Out the Way','Money So Big i Get Busy','D',NULL);
INSERT INTO `questions` VALUES (450,46,'Na którym utworze Drake\'a z albumu For All the Dogs (2023) gościnnie wystąpił Yeat?','Rich Flex','IDGAF','First Person Shooter','Slime You Out','B',NULL);
INSERT INTO `questions` VALUES (451,46,'Który album Yeata jako pierwszy trafił do top 10 listy Billboard 200?','Up 2 Me','Afterlyfe','2 Alive','Lyfestyle','C',NULL);
INSERT INTO `questions` VALUES (452,46,'W którym roku urodził się Yeat?','1998','1999','2001','2000','D',NULL);
/*!40000 ALTER TABLE `questions` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;


-- konto demo administratora (haslo: tunecheck, hash bcrypt z password_hash)
INSERT INTO `admins` (`id`, `username`, `password`, `token`) VALUES (1, 'admin', '$2y$10$CJEkf1V8f4Nn7eOuBHdEtOmGpufNldeor9jlM8fb90LB3IUvH3HIO', NULL);
